spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relay
    username: aditya
    password: cm9vdA==
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092   # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializer for the key
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializer for the value

config:
  topic: consumer1
  group: group1